version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
         - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql